options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init
        terraform apply -auto-approve \
